version: '3.1'
services:
  php:
    build: docker/php
    depends_on:
      - mongo
    volumes:
      - .:/var/app
    networks:
      - ddd-mongo

  mongo:
    image: mongo:4.0
    ports:
      - 8085:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - ddd-mongo

networks:
  ddd-mongo:
    driver: bridge